spring:
  cloud:
    gateway:
      routes:
        - id: timetable-route
          predicates:
            - Path=/api/timetable**
          uri: lb://TIMETABLE-SERVICE
          filters:
            - RewritePath=/api/timetable(?<segment>.*), $\{segment}
            - RewriteLocationResponseHeader=AS_IN_REQUEST, Location, localhost:8080/api/timetable
