spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/timetable
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    open-in-view: false
timeApi:
  endpoint: http://worldtimeapi.org/api/timezone
  timezone: Europe/Warsaw
