spring:
  application:
    name: gateway-service
  profiles:
    active: development
  config:
    import: optional:configserver:http://localhost:8888
#  cloud:
#    config:
#      label: 005-Reactive-services
      #fail-fast: true
      #request-connect-timeout: 10
      #request-read-timeout: 10