spring:
  application:
    name: timetable-service
  profiles:
    active: development
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      label: timetable-services
      #fail-fast: on
      #request-connect-timeout: 10
      #request-read-timeout: 10
